import { e as createAstro, f as createComponent, r as renderTemplate, h as renderComponent, m as maybeRenderHead, g as addAttribute, k as renderTransition } from '../astro_bf1117ea.mjs';
import { a as $$MainLayout, b as animalsJson, $ as $$Icon, c as $$Loader } from './Animals_cd45b04a.mjs';
/* empty css                          *//* empty css                             */import 'clsx';
import 'html-escaper';
/* empty css                          */import 'svgo';
/* empty css                             */
const $$Astro = createAstro();
const $$id = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$id;
  const animals = animalsJson;
  const animal = animals.find((el) => el.id === Number(Astro2.params.id));
  animals.filter((el) => el.id !== Number(Astro2.params.id));
  const alt = animal.lifespan;
  return renderTemplate`${renderComponent($$result, "MainLayout", $$MainLayout, { "title": animal.name }, { "default": ($$result2) => renderTemplate`${maybeRenderHead()}<section class="animal"><div class="container animal__container"><div class="animal__top"><div class="animal__top--left"><div class="animal__name"><h3 class="heading-third animal__name--text">${animal.name}</h3>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon animal__icon--1", "name": "mdi:paw" })}</div><ul class="animal__infos"><li class="animal__info"><strong>scientific name :&nbsp;</strong>${animal.scientific_name}</li><li class="animal__info"><strong>top speed :&nbsp;</strong>${animal.top_speed} km/h
</li><li class="animal__info"><strong>order :&nbsp;</strong>${animal.order}</li></ul></div><div class="animal__top--right">${renderComponent($$result2, "Loader", $$Loader, {})}<img${addAttribute(animal?.image_1, "data-src")}${addAttribute(alt, "alt")} class="animal__image lazy"${addAttribute(renderTransition($$result2, "ez4apgtd", "", "animalphoto"), "data-astro-transition-scope")}></div></div><div class="animal__mid1"><!-- Card --><div class="animal__card animal__card--short"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">Size</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "fluent:slide-size-24-regular" })}</div><div class="animal__card--details"><p class="paragraph">${animal.size}</p></div></div><!-- Card --><div class="animal__card animal__card--short"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">LifeSpan</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "fluent:info-24-regular" })}</div><div class="animal__card--details"><p class="paragraph">${animal.lifespan}</p></div></div><!-- Card --><div class="animal__card animal__card--short animal__card--orange"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">
Conservation Status
</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "bi:book" })}</div><div class="animal__card--details"><p class="paragraph">${animal.conservation}</p></div></div></div><div class="animal__mid2"><div class="animal__card animal__card--long"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">Distribution</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "carbon:location" })}</div><div class="animal__card--details"><p class="paragraph">${animal.distribution}</p></div></div><div class="animal__card animal__card--short"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">Coevolution</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "clarity:avatar-line" })}</div><div class="animal__card--details"><p class="paragraph">${animal.species}</p></div></div></div><div class="animal__bottom"><div class="animal__card animal__card--short"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">Nutrition</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "mdi:food-drumstick-outline" })}</div><div class="animal__card--details"><p class="paragraph">${animal.nutrition}</p></div></div><div class="animal__card animal__card--short animal__card--image">${renderComponent($$result2, "Loader", $$Loader, {})}<img${addAttribute(animal.image_2, "data-src")}${addAttribute(alt, "alt")} class="lazy"></div><div class="animal__card animal__card--short"><div class="animal__card--name"><h4 class="heading-third animal__card--name-text">Lifestyle</h4>${renderComponent($$result2, "Icon", $$Icon, { "class": "icon animal__icon", "name": "ph:heart" })}</div><div class="animal__card--details"><p class="paragraph">${animal.lifestyle}</p></div></div></div></div></section>` })}`;
}, "C:/Users/Youness/Desktop/Crocopark/src/pages/Animal/[id].astro", "self");

const $$file = "C:/Users/Youness/Desktop/Crocopark/src/pages/Animal/[id].astro";
const $$url = "/Animal/[id]";

export { $$id as default, $$file as file, $$url as url };
